### ISSUE TITLE
[Info] Synology Nas

### ISSUE THREAD

**Issue by gborri** [Jalle19/node-ffmpeg-mpegts-proxy#10]
I whould like to use it on synology nas on which is possible to install ffmpeg but not avconv.
Do you think is it possible? if not do you think is possible to adeguate your app?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
simple call it with parameter "a"

-a ffmpeg ...

**Comment by Jalle19** [comment]
You'll need NodeJS installed as well, not sure if that's available or not.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
it is ... !!!

**Comment by gborri** [comment]
Thank for your prompt answer. I will try your suggestion tonight if i have
chance. Just one question: which is the difference between avconv and
ffmpeg? in my Nas there's a transcoding chipset that could be used instead
of cpu.

Il giorno ven 30 ott 2015 18:34 c-o-m-m-a-n-d-e-r <notifications@github.com>
ha scritto:

> it is ... !!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jalle19/node-ffmpeg-mpegts-proxy/issues/10#issuecomment-152596023>
> .
>
-- 

Giovanni

**Comment by c-o-m-m-a-n-d-e-r** [comment]
hey,
avconv is a fork from ffmpeg (some developers changed the team)

which syno do you have? think you can't use ffmpeg/avconv with the encoder chip!

**Comment by gborri** [comment]
i have ds214play. i have found this mod of ffmpeg: https://www.dropbox.com/s/g02eelw6vwfjfd3/FFmpegWithDTS-evansport-1.0-0005.spk. now iwould like to make everything work then i will try his version of ffmpeg

**Comment by gborri** [comment]
i've got this error. I'm new to node.js.

DiskStation> node -v
v0.12.6

DiskStation> node node-ffmpeg-mpegts-proxy.js -a ffmpeg -p 9128 -s /volume1/node-ffmpeg-mpegts-proxy/config/
module.js:338
    throw err;
          ^
Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/volume1/node-ffmpeg-mpegts-proxy/node-ffmpeg-mpegts-proxy.js:4:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
try : npm install -g yargs

**Comment by gborri** [comment]
done. but seams not yet working. It seems that can't find modules, but there is.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
try the command in the same folder then your script

npm install yargs

**Comment by Jalle19** [comment]
It should be enough to run `npm install` from the project folder to get all dependencies.

**Comment by gborri** [comment]
it works.

thanks
Giovanni

On Tue, Nov 3, 2015 at 11:22 AM Sam Stenvall <notifications@github.com>
wrote:

> It should be enough to run npm install from the project folder to get all
> dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jalle19/node-ffmpeg-mpegts-proxy/issues/10#issuecomment-153308172>
> .
>
-- 

Giovanni

**Comment by Jalle19** [comment]
Thanks, that would mean the existing instructions in the README apply to Synology DiskStation as well. Good to know.

**Comment by Yasston** [comment]
Just for information, installation doesn't work on Synology DS916+.
The npm install command gives this error : 
```
> sleep@4.0.0 install /volume1/Projets/mpegtsprox/node-ffmpeg-mpegts-proxy/node_modules/sleep
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
[...]

```
I believe it is linked to the problem faced here : [(https://github.com/Storj/storjshare-daemon/issues/8)]
installing being root with this command :  `npm install --unsafe-perm`
let's you get past the errors, but when trying to launch the app you get
```
module.js:540
    throw err;
    ^
Error: Cannot find module 'sleep'
```
I didn't bother going further and installed a Docker image, which is working fine

**Comment by findingneo17** [comment]
Seems I have a similar issue. Trying to run on Synology DS918+. Given I'm new to node.js not exactly sure what's going wrong here...

hts@Diskstation:~$ node -v
v8.9.4

hts@Diskstation:~$ node ~/tvh/node-ffmpeg-mpegts-proxy/node-ffmpeg-mpegts-proxy.js -l 192.168.1.238 -p 9128 -a ffmpeg -s ~/tvh/hts.channels.json
module.js:540
    throw err;
    ^

Error: Cannot find module './build/Release/node_sleep.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/git/node-ffmpeg-mpegts-proxy/node_modules/sleep/index.js:2:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
