### ISSUE TITLE
Support specifying HTTP proxy per stream

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/node-ffmpeg-mpegts-proxy#11]
Some streams may require a different HTTP proxy per stream. ffmpeg apparently uses whatever proxy is specified in the `http_proxy` environment variable so it should be possible to leverage that.

**Comment by Jalle19** [comment]
Should be possible to pass environment variables to `spawn()`, just need to merge with `process.env` before doing it.

**Comment by djbeirut** [comment]
any progress on this?

**Comment by Jalle19** [comment]
Not yet.
