### ISSUE TITLE
generic ffmpeg filtering

### ISSUE THREAD

**Issue by wdehoog** [Jalle19/node-ffmpeg-mpegts-proxy#13]
Hi, 

Thank you for your great tool. I hope to use it to filter the audio channel from the tvh stream which will allow mpd to play it on my stereo. This since the radio stations are also sent as mpeg-ts and I cannot get mpd to handle this.

It would be nice to have all ffmpeg options in the source file instead of hardcoded in options.js. This way all ffmpeg operations can be configured.

Another wish would be to get the source url as a parameter like:
http://localhost:9123/tomp2?source=http://192.168.4.106:9981/stream/channelid/745494892

**Comment by Jalle19** [comment]
This tool is explicitly for converting any stream into MPEG-TS, so if mpd can't handle that I don't think you'll get much use of this app without modifying it to suit your needs.

What do you mean by embedding the source URL in the stream URL like that? What's the use case?

**Comment by wdehoog** [comment]
The use case is a tvheadend installation with a lot of radio station channels. I do not want to create an entry in the sources.json for every station. 

I know your tool is explicitly for converting any stream into MPEG-TS but it's architecture is excellent to have it transcode any stream into another one (whatever ffmpeg supports).

**Comment by Jalle19** [comment]
I'm not sure I understand how a stream URL parameter will help you here?

**Comment by Jalle19** [comment]
Closing this, like I said the main purpose of this tool is to output MPEG-TS. If you want it to do something else you are free to hack your local copy of it.
