### ISSUE TITLE
Q : can source be node self input stream

### ISSUE THREAD

**Issue by nvcken** [Jalle19/node-ffmpeg-mpegts-proxy#15]
I see source is an external input. Is it can be self likes
`rtmp://localhost:1935/live`
This mean, devices will publish their record data to node-ffmpeg-mpegts-proxy via `rtmp://localhost:1935/live`, then node server serves HLS via node channel ( `"url": "/channel1"`)

**Comment by Jalle19** [comment]
The source can be anything that ffmpeg/avconv can handle, including things running on localhost.

**Comment by Jalle19** [comment]
Closing this since it's answered.
