### ISSUE TITLE
Not able to play the channel on iOS

### ISSUE THREAD

**Issue by windyin** [Jalle19/node-ffmpeg-mpegts-proxy#16]
Seems the streaming generated is not able to play on iOS devices. Though I wrote a m3u8 file to contain the streaming
______________________
#EXTM3U
#EXTINF:-1,CNN News
http://example.com:38989/channel1

**Comment by hummans** [comment]
Same problem, i have been trying for to long with this powerfull tool to make output streams on hls, without sucess. Ok i think i find a way , we need to use Byte Range segmentation for m3u8 file, tested with flowplayer wordpress,. But it plays with drops. How can we fix this?

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.010000,
#EXT-X-BYTERANGE:1617552@0
http://example.com:9128/channel11
#EXTINF:10.010000,
#EXT-X-BYTERANGE:1579764@1617552
http://example.com:9128/channel11
#EXTINF:10.010000,
#EXT-X-BYTERANGE:1567356@3197316
http://example.com:9128/channel11
#EXTINF:10.010000,
#EXT-X-BYTERANGE:1602136@4764672
http://example.com:9128/channel11
#EXTINF:2.602000,
#EXT-X-BYTERANGE:386152@6366808
http://example.com:9128/channel11
#EXT-X-ENDLIST

**Comment by Jalle19** [comment]
I have no idea about any of this. I wrote this tool to pipe random streams to tvheadend, but it seems most people are using it for other things these days. I don't even have an iOS device so I can't help you much.

**Comment by hummans** [comment]
Found for HLS output we need to change from '-f', 'mpegts' to '-f', 'hls', '-hls_flags', 'single_file', '-hls_time', '2', '-hls_list_size', '0' and use ffmpeg instead of avconv.  it works on apple devices. 
But now , How to set: Access Control Allow Origin, crossdomain origin, to make this hls output to play on html5 browsers on any device? example with flowplayer http://demos.flowplayer.org/api/hlsjs.html and for testing the stream http://dailymotion.github.io/hls.js/demo/  it tells problem is cross origin.
Thank You Jalle19

**Comment by hummans** [comment]
i try to add on node-ffmpeg-mpets-proxy.js on line 78: 

	if (request.method === 'OPTIONS') {
			console.log('!OPTIONS');
			var headers = {};
			// IE8 does not allow domains to be specified, just the *
			// headers["Access-Control-Allow-Origin"] = req.headers.origin;
			headers["Access-Control-Allow-Origin"] = "*";
			headers["Access-Control-Allow-Methods"] = "POST, GET, PUT, DELETE, OPTIONS";
			headers["Access-Control-Allow-Credentials"] = false;
			headers["Access-Control-Max-Age"] = '86400'; // 24 hours
			headers["Access-Control-Allow-Headers"] = "X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept";
			response.writeHead(200, headers);
			response.end();
			return;
	}

on vlc works but not in web player, same CORS issue. What i am making wrong?

**Comment by Jalle19** [comment]
Closing this since the purpose of the tool is to output MPEG-TS. If your favorite player on iOS can't play that I suggest you switch to another player.
