### ISSUE TITLE
Broken output for some devices

### ISSUE THREAD

**Issue by bartwe2** [Jalle19/node-ffmpeg-mpegts-proxy#17]
Hello, thanks for great tool. It works perfect when i playing stream from VLC on PC. But the same stream on SamsungTV is pixalated. It looks like [this](https://i.ytimg.com/vi/YDYNYJODBqo/maxresdefault.jpg). The same source restreamed by VLC looks great on SamsungTV. Is it possible to replace avconv by vlc? Or any trick for fix signal on TV?

**Comment by Jalle19** [comment]
Try with the latest version of avconv/ffmpeg. There may be some setting you have to tweak in order to get your TV to play the streams properly. This tool doesn't deal with the video at all so whatever your issue is it shouldn't be this software that is causing it.
