### ISSUE TITLE
Possible specifying avconv binary name per stream?

### ISSUE THREAD

**Issue by beginho** [Jalle19/node-ffmpeg-mpegts-proxy#20]
Hello,

Is it possible to specify avconv binary name for every stream?
So next to the name, provider, url, source... in sources.json to have something like: 

```
"name": "Channel 1",
"provider": "Provider",
"url": "/channel1",
"source": "http://somehost:31000/stream1.ts",
"avconv": "ffmpeg1"
```

as I often need to use several versions of ffmpeg to support all input streams I need...

Thanks in advance

**Comment by Jalle19** [comment]
Not at the moment, but it shouldn't be too hard to implement. Are you up for it?

**Comment by beginho** [comment]
Work like a charm... youre the man!
thx

**Comment by Jalle19** [comment]
Glad to hear!
