### ISSUE TITLE
Option that enable or disable an stream in sources.json?

### ISSUE THREAD

**Issue by beginho** [Jalle19/node-ffmpeg-mpegts-proxy#25]
Hi again,

thanks for solving avconv path per stream 👍 

> avconv path on a per-stream basis (closes #20)

As title says, I think this kind of switch will be really useful, since sometimes is needed to temporary disable certain stream....
So to avoid deleting one stream's section in sources when you want to temporary disable it 
and adding it back when you want to get stream back, 
there could be and `"active": "yes|no"` line or something similar defined in sources.   

Regards,
Beginho

**Comment by Jalle19** [comment]
Why do you need to disable them?

**Comment by beginho** [comment]
-Lets say source of specific stream is bad for some reason, and you need time to fix/change it, ok?
To avoid streaming of an "corrupted" stream, you can use an off/on switch at stream section and disable it until source is fixed/changed... 
-Or if source is temporary dead, i think you will agree that its not needed to start avconv at all, and using resources for nothing, cause node-ffmpeg-mpegts-proxy will try to start avconv like forever.
When source is back, then you can simply enable stream...
And many other situations are on my mind, but please, if you find this silly, please ignore my question and close the case, Im more then satisfied with current possibilities... thanks much!

Regards,
Beginho

**Comment by Jalle19** [comment]
Well, since you'd have to edit the configuration anyway to change the enabled flag, why not just remove the channel entry until it's been fixed.

Maybe it would be better to add some throttling so it doesn't try to spawn avconv processes as fast as possible?

**Comment by beginho** [comment]
> Maybe it would be better to add some throttling so it doesn't try to spawn avconv processes as fast as possible?

Thats another way to go.. why not

**Comment by Jalle19** [comment]
Closing this in favor of https://github.com/Jalle19/node-ffmpeg-mpegts-proxy/issues/27
