### ISSUE TITLE
Source change is not detected

### ISSUE THREAD

**Issue by nbittmann** [Jalle19/node-ffmpeg-mpegts-proxy#29]
For some reason the source change is not working anymore since the last update?

**Comment by Jalle19** [comment]
Are you sure? Nothing in the logs? Do you know a version where it still works?

**Comment by nbittmann** [comment]
Nothing in the logs I can get you some more detail tomorrow morning

**Comment by Jalle19** [comment]
Okay. I'll try replicating myself, it's probably an easy fix.

**Comment by nbittmann** [comment]
Actually how can I check the version ? 

Git head is "bf58db812c7f38b212f16dd6f4ae73ba4b34719f"

If that helps that's the last working version for me the one that does not work is the current one cloned about 3 days ago.

**Comment by NMichas** [comment]
Tested with commit e12c905:
* Ubuntu 16.04 server, node 6.9.5: Change detection works fine.
* macOS 10.12.2, node 6.9.1: Change detection does not work (nothing in the logs).

**Comment by Jalle19** [comment]
@nbittmann are you also using this on macOS?

**Comment by Jalle19** [comment]
@NMichas thanks for testing. Can you try running `npm update chokidar` on your macOS installation and see if that fixes the issue?
