### ISSUE TITLE
can it be used for preloading/caching .ts or m3u8 streams ?

### ISSUE THREAD

**Issue by isayed** [Jalle19/node-ffmpeg-mpegts-proxy#34]
Hi, 
thanks for the project. I am going to give it a go but thought I would formally ask (as it is not spelled out in the doco), if this would work in a setup where a number of minutes preloading/caching is required before the stream should be available for clients ? in other words, can I use some optional params to do that ?

Thanks

**Comment by Jalle19** [comment]
If ffmpeg supports that then it's possible.

**Comment by isayed** [comment]
Thanks , I tried avconv but did not really work for me. I will give ffmpeg a go too ..
where do you configure whether to use avconv or ffmpeg ?

**Comment by Jalle19** [comment]
See the README (`-a` switch)
