### ISSUE TITLE
error cannot read property 'F_OK' of undefined

### ISSUE THREAD

**Issue by isayed** [Jalle19/node-ffmpeg-mpegts-proxy#35]
I am receving the following error trying to run the app using the example in the doc..
i have avconv installed on my machine ..

```
node-ffmpeg-mpegts-proxy/node_modules/command-exists/lib/command-exists.js:12
    access(commandName, constants.F_OK,
                                 ^
TypeError: Cannot read property 'F_OK' of undefined
    at fileNotExists
```

Any ideas ? 
Thanks

**Comment by Jalle19** [comment]
Can you remove `node_modules` and run `npm install` again?

**Comment by isayed** [comment]
done and this fixed the problem thanks...
i am having another problem though where the stream drops and seeing lots of
```
avconv exited with code 0
info: avconv started successfully
debug: avconv exited with code 0
info: avconv started successfully
error: avconv exited with code 1
```
I am also not sure if I can use the module to cache/buffer/preload the stream so that I don't get drops for the m3u8 stream (the main reason I wanted to try this). I tried all sort of config parameters to avconv but can't get this to really work for that. Any thoughts ? Is this a possible use case ?

Thanks again

**Comment by Jalle19** [comment]
Try getting the command you want to use to work standalone by directly running ffmpeg. Once you know it works you can configure it as a source.
