### ISSUE TITLE
[Feature request] Reload source before starting stream

### ISSUE THREAD

**Issue by nbittmann** [Jalle19/node-ffmpeg-mpegts-proxy#36]
Hi again,

I've got a bit of a special request for you, I use your tool quite heavily for IPTV however I need to refresh the URL before I start a stream I do this via an external python script but due to the fact that the software starts streaming immediately I usually run into the issue that I need to wait for at least one restart to get the new URL that was put in via the pre-script.

Now my request as I'm not any good with node:

Can we somehow change the behaviour to ensure the sources have been reloaded before starting a stream to the client? That would prevent having to wait for at least one restart and should speed things up.

Thanks

**Comment by Jalle19** [comment]
If you add a small delay to the prescript, wouldn't that mean the sources get reloaded before the prescript has run, thus giving you the correct URL the first time?

**Comment by Jalle19** [comment]
@nbittmann any update on this?

**Comment by nbittmann** [comment]
Sorry for the late reply got stuck on other stuff yes this seems to do the trick

**Comment by Jalle19** [comment]
Thanks for the update!
