### ISSUE TITLE
avconv -re option breaks some inputs

### ISSUE THREAD

**Issue by jfath** [Jalle19/node-ffmpeg-mpegts-proxy#38]
I'm streaming to tvheadend from an IPTV encoder that puts out http, rtsp, or rtp.

Testing with an http source stream, the video would start and play smoothly for a few seconds, then begin a cycle of play a few seconds, buffer, skip, play a few seconds, buffer, etc.  I noticed options.js forces the -re option for the avconv input.  Commenting that line makes the video play smoothly.

I know extra options can be added in the sources file, but don't think there's a way to over-ride the forced -re option?  If not, maybe we need another to turn off -re?

BTW, I'm using the proxy for http->http because the pre command allows using an IR blaster which is really handy for those of us in the US that still are forced to use cable boxes.  My 4 core xeon vm shows less than 4% cpu usage while running the stream through the proxy, so no performance worries.

**Comment by Jalle19** [comment]
I guess we could add an optional `realtime` option that defaults to true.

**Comment by jfath** [comment]
I wouldn't want to make a change that would break things for existing users, but it does appear that the -re option is intended to fake a video streaming device by reading from a file.
I think you're suggesting the new option should default to current (-re) configuration and setting it would eliminate -re?  That seems like the right thing to do.

**Comment by Jalle19** [comment]
Yeah, default would be to keep current behavior

**Comment by jfath** [comment]
That would be great.  I'm working on a series of articles showing setup and configuration of Tvheadend using node-ffmpeg-mpegts-proxy to control and stream from set-top-boxes and hdmi encoders (mostly needed in the US).  Right now, I'm documenting how to comment -re because I didn't want to fork just for that change.  It would be much nicer to document the new option. [](https://jfathsite.wordpress.com/)

**Comment by jfath** [comment]
My sources file now looks like this:
    {
        "name": "523 STZEHD",
        "provider": "Smithville Digital",
        "url": "/523",
        "source": "http://192.168.222.90:8080/hdmi",
        "prescript": "/home/hts/tvh/pre.sh",
        "postscript": "/home/hts/tvh/post.sh",
        "realtime": "false"
    },
    {
        "name": "452 SHO2",
        "provider": "Smithville Digital",
        "url": "/452",
        "source": "http://192.168.222.90:8080/hdmi",
        "prescript": "/home/hts/tvh/pre.sh",
        "postscript": "/home/hts/tvh/post.sh",
        "realtime": "false"
    },
...etc...

But debug output says this:
2017-11-03T15:58:57.431Z - debug: Options passed to avconv: -re,-i,http://192.168.222.90:8080/hdmi,-vcodec,copy,-acodec,copy,-metadata,service_provider=Smithville Digital,-metadata,service_name=10 BIGTEN,-f,mpegts,pipe:1

Am I specifying the realtime switch incorrectly?  I triple checked that I'm using the updated sources file.

**Comment by jfath** [comment]
My bad, new switch should be "realtime": false
Your commit fixes the issue completely.  Thanks.
