### ISSUE TITLE
Allow multiple concurent views into the same channel  

### ISSUE THREAD

**Issue by Yasston** [Jalle19/node-ffmpeg-mpegts-proxy#40]
Hello, first of all thank you for your work.
I wanted to test if node-ffmpeg-mpegts-proxy would allow multiple concurent views into the same channel, even if the source iptv stream provider does not. In other words, can we proxy the IPTV stream so only the server will be seen as the "user" (from the iptv provider point of view) when multiple devices (on the same network) connect to the SAME channel on this side ?

It would seem that it does not work, I tried with two different VLC clients and I saw through netstat that two different ffmpeg processes were connecting to the IPTV provider..

Can I have your input on that ? I spent all day trying to find a proxy that would have this feature, but failed. It is also frustrating because I can see some other proxies out there that have such a feature, but are outputing Plex LiveTV compatible outputs, not something you could directly feed to a client such as VLC... See this project for example : https://hub.docker.com/r/xiaodoudoufr/plexiptv/

If you the feature is absent, would someone happen to know another project who would have it ?

Thanks

**Comment by Jalle19** [comment]
This project doesn't have that feature, but I'm sure it could be added without too much effort. tvheadend (tvheadend.org) has this feature, but it is a lot more complicated than a simply streaming proxy.

**Comment by Yasston** [comment]
I didn't know that ! I tested it and it seems like a default feature, nothing special to do. Thank you very much for your answer !
