### ISSUE TITLE
how do you use it with tvheadend ?

### ISSUE THREAD

**Issue by nileio** [Jalle19/node-ffmpeg-mpegts-proxy#49]
sorry i couldnt find the answer to this basic question ! you mentioned it was built for this but I couldnt really find how you configure tvheadend to use it?
I currently use pipe and it works but i want to try your solution because i have some issues with smooth streaming.
with IPTV automatic network , I specify a URL for the m3u8 list to generate muxes and associated IPTV services. does this tool provide an m3u8 list containing all services which can be used as the URL ?

Thanks!!

**Comment by Jalle19** [comment]
It was built for use with pipe://. This tool does not generate a playlist for tvheadend so I think for your case it's probably the wrong tool for the job.

**Comment by findingneo17** [comment]
Maybe try this?

http://jafath.blogspot.com/2017/11/tvheadend-for-users-in-us-part-2.html
