### ISSUE TITLE
Error: listen EAFNOSUPPORT with not ipv6 support

### ISSUE THREAD

**Issue by realPy** [Jalle19/node-ffmpeg-mpegts-proxy#5]
I have this error because i have disabled ipv6 support in my kernel.
I have to modify source to only listen on my ipv4 interface.
A little test of ipv6 will be great ;)

**Comment by Jalle19** [comment]
At what stage do you get this error? How did you modify it to make it work? And most importantly, why do you disable IPv6?

**Comment by realPy** [comment]
This error happening when you start the script.
I'll modify the "server.listen(argv.port, '::'); // listen on both IPv4 and IPv6" with my IPV4 lan adress
This device not use ipV6 et never use it and for some security reason, i'll disable IPV6 on device that not use it.
