### ISSUE TITLE
Try with UDP Multicast stream to HTTP and not work

### ISSUE THREAD

**Issue by NangenX** [Jalle19/node-ffmpeg-mpegts-proxy#50]
Hi, I just try to put the UDP format stream and convert to HTTP, and it's giving the avconv error 1, and when i replace to m3u8 link, it's working file.

Test in Ubuntu 16.04.05 TLS,  Docker images with Json file:
[
        {
                "name": "UDP Program",
                "provider": "TEST",
                "url": "/u1",
                "source": "udp://224.10.10.1:5000"
        }
]

**Comment by Jalle19** [comment]
You will probably need to mess with the input parameters to get a UDP multicast stream working. I suggest you run udpxy instead if all you want to do is convert UDP multicast to HTTP.

**Comment by NangenX** [comment]
Thanks, I have fixed with udpxy, and thank you for your reply. close issues
