### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by stefs22** [Jalle19/node-ffmpeg-mpegts-proxy#56]
I am beginner and still dont understand how to install this, advices?

**Comment by Jalle19** [comment]
Try the various methods in the README. If you rum into a specific issue you can ask for help about it here.

**Comment by stefs22** [comment]
i still not understand where to start.

**Comment by Jalle19** [comment]
Not sure I can help you then :shrug: Sorry

**Comment by stefs22** [comment]
i want to get link from youtube to use on my cctv system, how?
