### ISSUE TITLE
Adding Pre- Post Script for Channel

### ISSUE THREAD

**Issue by vigne** [Jalle19/node-ffmpeg-mpegts-proxy#7]
Hi,

first, thanks for the effort you put into this project. I really like it.

I was wondering if you see a possibility to provide a pre/post script when a channel starts/ends streaming? What I try to achieve with this, is, to bring up/down different network interface which represent distinct exit nodes of my VPN provider. I was thinking that this way, my linux host can stream geo-blocked content using TVHeadEnd. E.g. for German channels the interface pptp-germany will be started and stopped afterwards, while for UK channels the interface pptp-uk will be started. I guess you get the picture.

What's your opinion on this? 

Thanks again for your work.

Cheers,
Ralph

**Comment by Jalle19** [comment]
I guess it's not too much to ask, I'll look into it.

**Comment by Jalle19** [comment]
Check the latest commits and let me know if you need any other parts of the source configuration passed to the scripts. Currently only the URL is passed there but it's easy to add more parameters if necessary.

**Comment by vigne** [comment]
Wow, you're fast - great!
I'll try it either today or tomorrow evening.

Thanks a lot, and I'll report back when I tried.

Cheers,
Ralph

**Comment by vigne** [comment]
I realised just now, that I somehow managed to not send my thank mail you a couple of days ago. :-/
So here it is: Thanks a lot! I works great.

Now I need to figure out my routing tables to keep the host accessible for the clients, even when it's connected to the VPN, but that's a different story.

Cheers,
Ralph
