### ISSUE TITLE
Live Stream only stuttering

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [Jalle19/node-ffmpeg-mpegts-proxy#8]
Hey,
i have different Live Sources tested (Dreambox, tvheadend Server) and also tested with avconv and ffmpeg. 

Both isn't working well ... if i try the same call (ffmpeg as example) and create HLS Output, its working fine.

I read something about Buffering when using Network Input.

**Comment by Jalle19** [comment]
This application isn't really designed to take input and turn it into HLS, it's designed to do it the other way around. Or did I misunderstand you?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Hey,
yes i already make changes for transcoding (codecs not copy and so on) ... but i think i missunderstood this solution then ...

What i have read is that with network input i have to use a ring buffer, but never did this before!
overall your solution is a great idea ... thanks for sharing.

I have a good working ffmpeg command, when i let it run standalone it produces perfekt output (HLS) ... this command i tried with your script, the only thing is the output

**Comment by Jalle19** [comment]
Are you still having issues with this?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yes and no ... i'm actually testing with a raspberry pi 2 for transcoding ...
There i have to use gstreamer for Hardwaresupport.

Your script helped me to create a testcase for my needs.

I think you can close this for now
