### ISSUE TITLE
Sending too little info

### ISSUE THREAD

**Issue by skerit** [Jalle19/node-ffmpeg-mpegts-proxy#9]
The avconv/ffmpeg stream is now piped into the response, like this:

    stream.pipe(response);

This mostly works just fine, however sometimes the first chunk ffmpeg returns will cause tvheadend to close the connection (because it's incomplete metadata, or whatever)

I have made an ugly hack where the first 4 chunks are buffered, concatenated and sent, that seems to solve the problem for now.

*edit: Guess I'm wrong. It seems to happen less now, but sometimes it still fails

**Comment by Jalle19** [comment]
Did your workaround work? Please try to reproduce with the newest tvheadend master if you can.

**Comment by silid** [comment]
I had this problem - but trying a daily master build of TVHeadend has resolved it.

**Comment by Jalle19** [comment]
I'm gonna go ahead and close this then.

**Comment by skerit** [comment]
Sorry, didn't notice response.

The problem was actually the other way around: if the first chunk was *too big* tvheadend would fail.
But I'm glad upgrading to a newer version works out better.
